# CVP300 Week 3: Solar Radiation on a Tilted Surface

This notebook calculates the amount of solar radiation falling on a tilted surface. This is done using an EnergyPlus weather file and sun position calculations.

## Define site and tilted surface parameters

In [2]:
latitude_angle=64.13
slope_angle=30
surface_azimuth_angle=0

## Import the epw file, add column names, add date index and select relevant columns

In [3]:
import pandas as pd
df=pd.read_csv('ISL_Reykjavik.040300_IWEC.epw', skiprows=8, header=None)
names=['Year', 'Month', 'Day', 'Hour', 'Minute', 'Data Source and Uncertainty Flags', 'Dry Bulb Temperature', 
       'Dew Point Temperature', 'Relative Humidity', 'Atmospheric Station Pressure', 'Extraterrestrial Horizontal Radiation', 
       'Extraterrestrial Direct Normal Radiation', 'Horizontal Infrared Radiation Intensity', 'Global Horizontal Radiation', 
       'Direct Normal Radiation', 'Diffuse Horizontal Radiation', 'Global Horizontal Illuminance', 
       'Direct Normal Illuminance', 'Diffuse Horizontal Illuminance', 'Zenith Luminance', 'Wind Direction', 
       'Wind Speed', 'Total Sky Cover', 'Opaque Sky Cover (used if Horizontal IR Intensity missing)', 'Visibility', 
       'Ceiling Height', 'Present Weather Observation', 'Present Weather Codes', 'Precipitable Water', 
       'Aerosol Optical Depth', 'Snow Depth', 'Days Since Last Snowfall', 'Albedo', 'Liquid Precipitation Depth', 
       'Liquid Precipitation Quantity']
df.columns=names
df.index=pd.date_range(start=pd.datetime(2019,1,1),freq="1H",periods=365*24)
df=df[['Hour','Direct Normal Radiation', 'Diffuse Horizontal Radiation']]
df.head()

,Hour,Direct Normal Radiation,Diffuse Horizontal Radiation
2019-01-01 00:00:00,1,0,0
2019-01-01 01:00:00,2,0,0
2019-01-01 02:00:00,3,0,0
2019-01-01 03:00:00,4,0,0
2019-01-01 04:00:00,5,0,0

## Add day of year column

There are several approaches that can be used to add a 'Day of Year' column to this dataframe.

### Approach 1: Use a nested loop

This uses one loop inside another loop to create the list of 'day of year' values.

https://www.linkedin.com/learning/learning-python-2/loops

In [7]:
l=[]
for i in range(365):
    for _ in range(24):
        l.append(i+1)
df['Day of Year1']=l
df.head(25)

,Hour,Direct Normal Radiation,Diffuse Horizontal Radiation,Day of Year1
2019-01-01 00:00:00,1,0,0,1
2019-01-01 01:00:00,2,0,0,1
2019-01-01 02:00:00,3,0,0,1
2019-01-01 03:00:00,4,0,0,1
2019-01-01 04:00:00,5,0,0,1
2019-01-01 05:00:00,6,0,0,1
2019-01-01 06:00:00,7,0,0,1
2019-01-01 07:00:00,8,0,0,1
2019-01-01 08:00:00,9,0,0,1
2019-01-01 09:00:00,10,0,0,1
2019-01-01 10:00:00,11,0,0,1
2019-01-01 11:00:00,12,0,1,1
2019-01-01 12:00:00,13,0,10,1
2019-01-01 13:00:00,14,0,17,1
2019-01-01 14:00:00,15,0,15,1
2019-01-01 15:00:00,16,0,2,1
2019-01-01 16:00:00,17,0,0,1
2019-01-01 17:00:00,18,0,0,1
2019-01-01 18:00:00,19,0,0,1
2019-01-01 19:00:00,20,0,0,1
2019-01-01 20:00:00,21,0,0,1
2019-01-01 21:00:00,22,0,0,1
2019-01-01 22:00:00,23,0,0,1
2019-01-01 23:00:00,24,0,0,1
2019-01-02 00:00:00,1,0,0,2

### Approach 2: Use a nested loop as a list comprehension

The exact same process as shown in Approach 1 can be written in a shorthand version using a list comprehension.

https://www.linkedin.com/learning/python-essential-training-2/list-comprehension

In [8]:
df['Day of Year2']=[i+1 for i in range(365) for _ in range(24)]
df.head(25)

,Hour,Direct Normal Radiation,Diffuse Horizontal Radiation,Day of Year1,Day of Year2
2019-01-01 00:00:00,1,0,0,1,1
2019-01-01 01:00:00,2,0,0,1,1
2019-01-01 02:00:00,3,0,0,1,1
2019-01-01 03:00:00,4,0,0,1,1
2019-01-01 04:00:00,5,0,0,1,1
2019-01-01 05:00:00,6,0,0,1,1
2019-01-01 06:00:00,7,0,0,1,1
2019-01-01 07:00:00,8,0,0,1,1
2019-01-01 08:00:00,9,0,0,1,1
2019-01-01 09:00:00,10,0,0,1,1
2019-01-01 10:00:00,11,0,0,1,1
2019-01-01 11:00:00,12,0,1,1,1
2019-01-01 12:00:00,13,0,10,1,1
2019-01-01 13:00:00,14,0,17,1,1
2019-01-01 14:00:00,15,0,15,1,1
2019-01-01 15:00:00,16,0,2,1,1
2019-01-01 16:00:00,17,0,0,1,1
2019-01-01 17:00:00,18,0,0,1,1
2019-01-01 18:00:00,19,0,0,1,1
2019-01-01 19:00:00,20,0,0,1,1
2019-01-01 20:00:00,21,0,0,1,1
2019-01-01 21:00:00,22,0,0,1,1
2019-01-01 22:00:00,23,0,0,1,1
2019-01-01 23:00:00,24,0,0,1,1
2019-01-02 00:00:00,1,0,0,2,2

### Approach 3: Using the `dayofyear` function.

The values in the DataFrame index can be used to create the day of year list.

https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.Timestamp.dayofyear.html

In [9]:
l=[]
for x in df.index: l.append(x.dayofyear)
df['Day of Year3']=l
df.head(25)

,Hour,Direct Normal Radiation,Diffuse Horizontal Radiation,Day of Year1,Day of Year2,Day of Year3
2019-01-01 00:00:00,1,0,0,1,1,1
2019-01-01 01:00:00,2,0,0,1,1,1
2019-01-01 02:00:00,3,0,0,1,1,1
2019-01-01 03:00:00,4,0,0,1,1,1
2019-01-01 04:00:00,5,0,0,1,1,1
2019-01-01 05:00:00,6,0,0,1,1,1
2019-01-01 06:00:00,7,0,0,1,1,1
2019-01-01 07:00:00,8,0,0,1,1,1
2019-01-01 08:00:00,9,0,0,1,1,1
2019-01-01 09:00:00,10,0,0,1,1,1
2019-01-01 10:00:00,11,0,0,1,1,1
2019-01-01 11:00:00,12,0,1,1,1,1
2019-01-01 12:00:00,13,0,10,1,1,1
2019-01-01 13:00:00,14,0,17,1,1,1
2019-01-01 14:00:00,15,0,15,1,1,1
2019-01-01 15:00:00,16,0,2,1,1,1
2019-01-01 16:00:00,17,0,0,1,1,1
2019-01-01 17:00:00,18,0,0,1,1,1
2019-01-01 18:00:00,19,0,0,1,1,1
2019-01-01 19:00:00,20,0,0,1,1,1
2019-01-01 20:00:00,21,0,0,1,1,1
2019-01-01 21:00:00,22,0,0,1,1,1
2019-01-01 22:00:00,23,0,0,1,1,1
2019-01-01 23:00:00,24,0,0,1,1,1
2019-01-02 00:00:00,1,0,0,2,2,2

### Approach 4: Creating a list by incrementing when the Hour column is equal to 24

In [10]:
l=[]
i=1
for index,row in df.iterrows():
    l.append(i)
    if row['Hour']==24: i=i+1
df['Day of Year4']=l
df.head(25)

,Hour,Direct Normal Radiation,Diffuse Horizontal Radiation,Day of Year1,Day of Year2,Day of Year3,Day of Year4
2019-01-01 00:00:00,1,0,0,1,1,1,1
2019-01-01 01:00:00,2,0,0,1,1,1,1
2019-01-01 02:00:00,3,0,0,1,1,1,1
2019-01-01 03:00:00,4,0,0,1,1,1,1
2019-01-01 04:00:00,5,0,0,1,1,1,1
2019-01-01 05:00:00,6,0,0,1,1,1,1
2019-01-01 06:00:00,7,0,0,1,1,1,1
2019-01-01 07:00:00,8,0,0,1,1,1,1
2019-01-01 08:00:00,9,0,0,1,1,1,1
2019-01-01 09:00:00,10,0,0,1,1,1,1
2019-01-01 10:00:00,11,0,0,1,1,1,1
2019-01-01 11:00:00,12,0,1,1,1,1,1
2019-01-01 12:00:00,13,0,10,1,1,1,1
2019-01-01 13:00:00,14,0,17,1,1,1,1
2019-01-01 14:00:00,15,0,15,1,1,1,1
2019-01-01 15:00:00,16,0,2,1,1,1,1
2019-01-01 16:00:00,17,0,0,1,1,1,1
2019-01-01 17:00:00,18,0,0,1,1,1,1
2019-01-01 18:00:00,19,0,0,1,1,1,1
2019-01-01 19:00:00,20,0,0,1,1,1,1
2019-01-01 20:00:00,21,0,0,1,1,1,1
2019-01-01 21:00:00,22,0,0,1,1,1,1
2019-01-01 22:00:00,23,0,0,1,1,1,1
2019-01-01 23:00:00,24,0,0,1,1,1,1
2019-01-02 00:00:00,1,0,0,2,2,2,2

### Approach 5: Create a list by dividing the row number by 24 and rounding.

In [12]:
l=[]
i=1
for i in range(len(df)):
    l.append(int(i/24)+1)
df['Day of Year5']=l
df.head(25)

,Hour,Direct Normal Radiation,Diffuse Horizontal Radiation,Day of Year1,Day of Year2,Day of Year3,Day of Year4,Day of Year5
2019-01-01 00:00:00,1,0,0,1,1,1,1,1
2019-01-01 01:00:00,2,0,0,1,1,1,1,1
2019-01-01 02:00:00,3,0,0,1,1,1,1,1
2019-01-01 03:00:00,4,0,0,1,1,1,1,1
2019-01-01 04:00:00,5,0,0,1,1,1,1,1
2019-01-01 05:00:00,6,0,0,1,1,1,1,1
2019-01-01 06:00:00,7,0,0,1,1,1,1,1
2019-01-01 07:00:00,8,0,0,1,1,1,1,1
2019-01-01 08:00:00,9,0,0,1,1,1,1,1
2019-01-01 09:00:00,10,0,0,1,1,1,1,1
2019-01-01 10:00:00,11,0,0,1,1,1,1,1
2019-01-01 11:00:00,12,0,1,1,1,1,1,1
2019-01-01 12:00:00,13,0,10,1,1,1,1,1
2019-01-01 13:00:00,14,0,17,1,1,1,1,1
2019-01-01 14:00:00,15,0,15,1,1,1,1,1
2019-01-01 15:00:00,16,0,2,1,1,1,1,1
2019-01-01 16:00:00,17,0,0,1,1,1,1,1
2019-01-01 17:00:00,18,0,0,1,1,1,1,1
2019-01-01 18:00:00,19,0,0,1,1,1,1,1
2019-01-01 19:00:00,20,0,0,1,1,1,1,1
2019-01-01 20:00:00,21,0,0,1,1,1,1,1
2019-01-01 21:00:00,22,0,0,1,1,1,1,1
2019-01-01 22:00:00,23,0,0,1,1,1,1,1
2019-01-01 23:00:00,24,0,0,1,1,1,1,1
2019-01-02 00:00:00,1,0,0,2,2,2,2,2

### Approach 6: Use a loop to add lists together

In [14]:
l=[]
for i in range(365):
    l=l+[i+1]*24
df['Day of Year6']=l
df.head(25)

,Hour,Direct Normal Radiation,Diffuse Horizontal Radiation,Day of Year1,Day of Year2,Day of Year3,Day of Year4,Day of Year5,Day of Year6
2019-01-01 00:00:00,1,0,0,1,1,1,1,1,1
2019-01-01 01:00:00,2,0,0,1,1,1,1,1,1
2019-01-01 02:00:00,3,0,0,1,1,1,1,1,1
2019-01-01 03:00:00,4,0,0,1,1,1,1,1,1
2019-01-01 04:00:00,5,0,0,1,1,1,1,1,1
2019-01-01 05:00:00,6,0,0,1,1,1,1,1,1
2019-01-01 06:00:00,7,0,0,1,1,1,1,1,1
2019-01-01 07:00:00,8,0,0,1,1,1,1,1,1
2019-01-01 08:00:00,9,0,0,1,1,1,1,1,1
2019-01-01 09:00:00,10,0,0,1,1,1,1,1,1
2019-01-01 10:00:00,11,0,0,1,1,1,1,1,1
2019-01-01 11:00:00,12,0,1,1,1,1,1,1,1
2019-01-01 12:00:00,13,0,10,1,1,1,1,1,1
2019-01-01 13:00:00,14,0,17,1,1,1,1,1,1
2019-01-01 14:00:00,15,0,15,1,1,1,1,1,1
2019-01-01 15:00:00,16,0,2,1,1,1,1,1,1
2019-01-01 16:00:00,17,0,0,1,1,1,1,1,1
2019-01-01 17:00:00,18,0,0,1,1,1,1,1,1
2019-01-01 18:00:00,19,0,0,1,1,1,1,1,1
2019-01-01 19:00:00,20,0,0,1,1,1,1,1,1
2019-01-01 20:00:00,21,0,0,1,1,1,1,1,1
2019-01-01 21:00:00,22,0,0,1,1,1,1,1,1
2019-01-01 22:00:00,23,0,0,1,1,1,1,1,1
2019-01-01 23:00:00,24,0,0,1,1,1,1,1,1
2019-01-02 00:00:00,1,0,0,2,2,2,2,2,2

## Final dataframe

In [15]:
df

,Hour,Direct Normal Radiation,Diffuse Horizontal Radiation,Day of Year1,Day of Year2,Day of Year3,Day of Year4,Day of Year5,Day of Year6
2019-01-01 00:00:00,1,0,0,1,1,1,1,1,1
2019-01-01 01:00:00,2,0,0,1,1,1,1,1,1
2019-01-01 02:00:00,3,0,0,1,1,1,1,1,1
2019-01-01 03:00:00,4,0,0,1,1,1,1,1,1
2019-01-01 04:00:00,5,0,0,1,1,1,1,1,1
2019-01-01 05:00:00,6,0,0,1,1,1,1,1,1
2019-01-01 06:00:00,7,0,0,1,1,1,1,1,1
2019-01-01 07:00:00,8,0,0,1,1,1,1,1,1
2019-01-01 08:00:00,9,0,0,1,1,1,1,1,1
2019-01-01 09:00:00,10,0,0,1,1,1,1,1,1
2019-01-01 10:00:00,11,0,0,1,1,1,1,1,1
2019-01-01 11:00:00,12,0,1,1,1,1,1,1,1
2019-01-01 12:00:00,13,0,10,1,1,1,1,1,1
2019-01-01 13:00:00,14,0,17,1,1,1,1,1,1
2019-01-01 14:00:00,15,0,15,1,1,1,1,1,1
2019-01-01 15:00:00,16,0,2,1,1,1,1,1,1
2019-01-01 16:00:00,17,0,0,1,1,1,1,1,1
2019-01-01 17:00:00,18,0,0,1,1,1,1,1,1
2019-01-01 18:00:00,19,0,0,1,1,1,1,1,1
2019-01-01 19:00:00,20,0,0,1,1,1,1,1,1
2019-01-01 20:00:00,21,0,0,1,1,1,1,1,1
2019-01-01 21:00:00,22,0,0,1,1,1,1,1,1
2019-01-01 22:00:00,23,0,0,1,1,1,1,1,1
2019-01-01 23:00:00,24,0,0,1,1,1,1,1,1
2019-01-02 00:00:00,1,0,0,2,2,2,2,2,2
2019-01-02 01:00:00,2,0,0,2,2,2,2,2,2
2019-01-02 02:00:00,3,0,0,2,2,2,2,2,2
2019-01-02 03:00:00,4,0,0,2,2,2,2,2,2
2019-01-02 04:00:00,5,0,0,2,2,2,2,2,2
2019-01-02 05:00:00,6,0,0,2,2,2,2,2,2
...,...,...,...,...,...,...,...,...,...
2019-12-30 18:00:00,19,0,0,364,364,364,364,364,364
2019-12-30 19:00:00,20,0,0,364,364,364,364,364,364
2019-12-30 20:00:00,21,0,0,364,364,364,364,364,364
2019-12-30 21:00:00,22,0,0,364,364,364,364,364,364
2019-12-30 22:00:00,23,0,0,364,364,364,364,364,364
2019-12-30 23:00:00,24,0,0,364,364,364,364,364,364
2019-12-31 00:00:00,1,0,0,365,365,365,365,365,365
2019-12-31 01:00:00,2,0,0,365,365,365,365,365,365
2019-12-31 02:00:00,3,0,0,365,365,365,365,365,365
2019-12-31 03:00:00,4,0,0,365,365,365,365,365,365
2019-12-31 04:00:00,5,0,0,365,365,365,365,365,365
2019-12-31 05:00:00,6,0,0,365,365,365,365,365,365
2019-12-31 06:00:00,7,0,0,365,365,365,365,365,365
2019-12-31 07:00:00,8,0,0,365,365,365,365,365,365
2019-12-31 08:00:00,9,0,0,365,365,365,365,365,365
2019-12-31 09:00:00,10,0,0,365,365,365,365,365,365
2019-12-31 10:00:00,11,0,0,365,365,365,365,365,365
2019-12-31 11:00:00,12,0,2,365,365,365,365,365,365
2019-12-31 12:00:00,13,0,17,365,365,365,365,365,365
2019-12-31 13:00:00,14,0,24,365,365,365,365,365,365
2019-12-31 14:00:00,15,0,17,365,365,365,365,365,365
2019-12-31 15:00:00,16,0,2,365,365,365,365,365,365
2019-12-31 16:00:00,17,0,0,365,365,365,365,365,365
2019-12-31 17:00:00,18,0,0,365,365,365,365,365,365
2019-12-31 18:00:00,19,0,0,365,365,365,365,365,365
2019-12-31 19:00:00,20,0,0,365,365,365,365,365,365
2019-12-31 20:00:00,21,0,0,365,365,365,365,365,365
2019-12-31 21:00:00,22,0,0,365,365,365,365,365,365
2019-12-31 22:00:00,23,0,0,365,365,365,365,365,365
2019-12-31 23:00:00,24,0,0,365,365,365,365,365,365